services:
  database:
    image: mysql:8
    container_name: shopobre-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - shopobre-net

  backend:
    build: .
    container_name: shopobre-backend
    depends_on:
      - database
    restart: always
    environment:
      DB_DIALECT: mysql
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    networks:
      - shopobre-net

networks:
  shopobre-net:

volumes:
  mysqldata:
